#!/usr/bin/bash

if [[ "$#" -lt 1 ]]; then
	printf "Error! Missing Parameters!\n"
	exit 1
fi

words=0
chars=0
for arg in "$@"; do
	count=$(($words + 1))
	printf "[$count] ${arg} -> ${#arg}\n"
	chars=$((chars + ${#arg}))
	((words++))
done

printf "\nWords -> $words\nCharacters -> $chars\n"
