#!/usr/bin/env bash

# Este programa conta o número de palavras e número total e de 
# cada caractere inserido pelo usuário na linha de comando
#input: ./lensh arg1 arg2 ... argn

main() {
    words=1
    total=0
    for i in "$@"; do
        echo "[$((words++))] $i -> "${#i}""
        total=$((total + "${#i}"))
    done

    printf "\nwords: $((--words))\n"
    printf "characters -> $total\n"
}
main "$@"
printf "\n";
