#!/usr/bin/bash

readme() {
    if [[ -f "readme" ]]; then
        vim readme
    else
        if [[ -f "README" ]]; then
            vim README
        else
            echo "Nenhum arquivo 'readme' ou 'README' encontrado, criando 'README'..."
            vim README
        fi
    fi
}
readme
